### ISSUE TITLE
Determining country of purchase

### ISSUE THREAD

**Issue by adamniedzielski** [jackkinsella/confessions#100]
@jackkinsella 

We have three possible sources of customer's country:
- IP address
- country issuing the credit card, obtained from Stripe
- country provided by "business customer" when requesting an invoice

It's quite probable that at least one source doesn't match the other two. In fact, I can easily imagine a case when all three sources indicate different countries. What should we do in this case? Should we just ignore this fact and establish a certain order in which we pick the "country of purchase"?

I believe that the order should be:
- country provided by "business customer"
- country from Stripe if this is an individual customer
- IP address - very unlikely, because Stripe seems to return the country consistently

#### Storing the data

Should we store the country from Stripe in our database or is it enough that we can fetch it later on? Should we store the country from IP address or is it enough that we can resolve it again later on?

**Comment by jackkinsella** [comment]
1. yes, I agree with your ordering. 

2. please store the data from Stripe locally. If, for some weird reason, Stripe were to cancel my account and I couldn't get access to the data again, then it's possible Germany would retrospectively tax me with a "worst case scenario".

3. please store IP country as well because I'm not sure if this algorithm might change in future to give different answers for the same IPs. (plus symmetry with point 2)

**Comment by adamniedzielski** [comment]
I agree that storing the data on our side makes sense. This is a safe move and definitely recommended by "good engineering practices".
