### ISSUE TITLE
Customer support messages

### ISSUE THREAD

**Issue by adamniedzielski** [jackkinsella/confessions#18]
Do we want to handle customer support in the similar way it is done for Oxbridge Notes? This means:
1. contact form in the application
2. contact request results in the email being sent to the admin
3. the rest of the communication is handled with emails

@josephdb Does this flow work well for you? Can you suggest some potential improvements or highlight the pain points?

There are a couple services which allow to fully externalize customer support. For instance:
1. https://www.intercom.io/
2. https://customer.io/
3. https://www.uservoice.com/widget/
4. https://www.groovehq.com/
5. https://besnappy.com
6. https://userdeck.com/conversations/

The first two are really expensive and complex, but the rest looks more lightweight and is cheaper. @jackkinsella What do you think about it?

**Comment by josephdb** [comment]
I'm pretty speedy and comfortable moving between gmail for communication and the admin panel for checking order and customer info – I think the integration and complexity required to move to a service instead would probably be counterproductive (last time we tried it didn't add anything but complications). But I'm open to being convinced!

In terms of improving the current flow, the contact form email provides us with links to previous orders (if present) along with the message for customers who are logged in, but instead of linking to the order page in the back end, the link leads to the order downloads page. If it could lead to the order page instead that would be more helpful.

That's the only thing I can think of at the mo, but I'll pay attention as I go about customer service this week and look out for any other areas with room for optimization.

**Comment by jackkinsella** [comment]
Yea, I'll back up Joe up on this one. We experimented with a few of the above before, and overall we were less productive because we missed the features in Google Mail. 

(That said, I might maybe experiment with intercom.io for on-site acquisition)

**Comment by adamniedzielski** [comment]
Thanks for your feedback. It's really great that we have this previous experience and we can choose solutions which really work in our case :smile: Let's go with custom, simple solution then!
