### ISSUE TITLE
Buy as guest (if possible)

### ISSUE THREAD

**Issue by jackkinsella** [jackkinsella/confessions#30]
I've read many reports that this increases conversion rates substantially... thus, ideally, we just collect email address and don't ask readers to register (behind the scenes though, it's fine for us to have users with passwords or whatever)

**Comment by jackkinsella** [comment]
I say "if possible" because there may be complications with taxation compliance, depending on what data we receive from Stripe.

**Comment by adamniedzielski** [comment]
I'm thinking about the buying process with exactly this use case in mind. We can collect the email address in the Stripe popup and generate a user account behind the scenes, without the customer even knowing about this.

We can go further down this road and avoid using passwords at all. When a user want to sign in we just send an email containing a special sign-in link straight to their mailbox. I believe this is a good idea in our case, because only a small percentage of users will go back to our site to re-download their order. More about this: http://sakurity.com/blog/2015/04/10/email_password_manager.html
