### ISSUE TITLE
Switch Stripe to production

### ISSUE THREAD

**Issue by adamniedzielski** [jackkinsella/confessions#67]
@jackkinsella You have to activate the Stripe account. I recommend to do it in advance, because I don't know how long the process is.

BTW: Be careful not to upload the book to production until we switch Stripe to production. Anyone would be able to download it using the test credit cards!

**Comment by jackkinsella** [comment]
I have the form pre-filled and will send it this afternoon once we have the terms and conditions page done (apparently they inspect).

**Comment by jackkinsella** [comment]
It was instantaneous :) :)

They gave me a few pointers:

Before you go live, you might want to double check that you've done these things.

**Use your Live Secret Key**
In order to make live charges, instead of test charges, you have to use your Live Secret Key when making API calls to Stripe. Make sure to configure this key properly on your production servers.

**Use your Live Publishable Key with Stripe.js**
If you're using Checkout or Stripe.js, you'll need to also make sure to use your Live Publishable Key on your payment pages. Both your publishable and secret keys need to be live in order to work together.

**Enable HTTPS on your site**
You can only make charges if your site is served over HTTPS, whether or not you're using Checkout or Stripe.js. If you aren't using Checkout or Stripe.js, you'll need to take additional steps to be fully PCI compliant.

**Comment by adamniedzielski** [comment]
I switched Stripe keys in production which means that the test card no longer works, but we can safely upload the book to production.

Do you think that we should put a temporary notice that the book hasn't launched yet?

**Comment by jackkinsella** [comment]
I'm going to take that risk. Essentially the book is production ready anyway, it's been professionally edited and I just want to do one last proof-reading pass myself. But it's probably good enough already.
